gantt
  title Project activity
  dateFormat YYYY-MM-DD
  section Inst
    Job X-00A (st-c01)       :ins1, 2023-01-01, 2023-01-14
    Job X-10B (st-x05)       :after ins1, 2023-01-30
  section Tuning
    Job Y-10C (st-x01)       :tuning1, 2023-01-20, 10d
    Job Y-00D (st-x05)       :after tuning1, 2023-02-12
  section Testing
    Job Z-10C (st-x01)       :2023-02-01, 14d
    Job Z-00D (st-x05)       :10d