quadrantChart
  title Distribution evaluation
  x-axis Low matching allocation --> High matching allocation
  y-axis Highly problematic  --> Low problematic
  quadrant-1 Best deal
  quadrant-2 The budget is broken
  quadrant-3 Risky plan
  quadrant-4 Deadline is broken
  Distribution A: [0.7, 0.9]
  Distribution B: [0.4, 0.4]
  